/**
 * Audio assets by voice profile.
 * Each key is a vocabulary id.
 */

const AUDIO_ASSETS_FEMENINA: Record<string, any> = {
    // Dashboard
    'yo': require('../assets/audio/femenina/dashboard/yo.mp3'),
    'comida': require('../assets/audio/femenina/dashboard/comida.mp3'),
    'emociones': require('../assets/audio/femenina/dashboard/emociones.mp3'),
    'bano': require('../assets/audio/femenina/dashboard/baño.mp3'),
    'dormir': require('../assets/audio/femenina/dashboard/dormir.mp3'),
    'jugar': require('../assets/audio/femenina/dashboard/jugar.mp3'),
    'ropa': require('../assets/audio/femenina/dashboard/ropa.mp3'),
    'quiero': require('../assets/audio/femenina/dashboard/quiero_si.mp3'),
    'no-quiero': require('../assets/audio/femenina/dashboard/no_quiero_no.mp3'),
    'juguetes': require('../assets/audio/femenina/dashboard/juguetes.mp3'),
    'mi-dia': require('../assets/audio/femenina/dashboard/mi_dia.mp3'),
    'lacteos': require('../assets/audio/femenina/dashboard/lacteos.mp3'),
    'personas': require('../assets/audio/femenina/dashboard/personas.mp3'),
    'lugar': require('../assets/audio/femenina/dashboard/lugar.mp3'),
    'hora': require('../assets/audio/femenina/dashboard/hora.mp3'),
    'social': require('../assets/audio/femenina/dashboard/social.mp3'),
    'numeros': require('../assets/audio/femenina/dashboard/numeros.mp3'),
    'colores': require('../assets/audio/femenina/dashboard/colores.mp3'),

    // Core words
    'core-yo': require('../assets/audio/femenina/core/core-yo.mp3'),
    'core-quiero': require('../assets/audio/femenina/core/core-quiero.mp3'),
    'core-no': require('../assets/audio/femenina/core/core-no.mp3'),
    'core-me-gustaria': require('../assets/audio/femenina/core/core-me-gustaria.mp3'),
    'core-necesito': require('../assets/audio/femenina/core/core-necesito.mp3'),
    'core-no-me-gusta': require('../assets/audio/femenina/core/core-no-me-gusta.mp3'),
    'core-hola': require('../assets/audio/femenina/core/core-hola.mp3'),
    'core-gracias': require('../assets/audio/femenina/core/core-gracias.mp3'),

    // Yo
    'mi-nombre': require('../assets/audio/femenina/yo/mi-nombre.mp3'),
    'tengo-calor': require('../assets/audio/femenina/yo/tengo-calor.mp3'),
    'tengo-frio': require('../assets/audio/femenina/yo/tengo-frio.mp3'),
    'tengo-hambre': require('../assets/audio/femenina/yo/tengo-hambre.mp3'),
    'tengo-sed': require('../assets/audio/femenina/yo/tengo-sed.mp3'),
    'estoy-cansado': require('../assets/audio/femenina/yo/estoy-cansado.mp3'),
    'me-duele': require('../assets/audio/femenina/yo/me-duele.mp3'),
    'me-llamo': require('../assets/audio/femenina/yo/me-llamo.mp3'),
    'yo-soy': require('../assets/audio/femenina/yo/yo-soy.mp3'),
    'mi-cumple': require('../assets/audio/femenina/yo/mi-cumple.mp3'),
    'tengo-x-anos': require('../assets/audio/femenina/yo/tengo-x-anos.mp3'),

    // Emociones
    'calma': require('../assets/audio/femenina/emociones/calma.mp3'),
    'alegria': require('../assets/audio/femenina/emociones/alegria.mp3'),
    'tristeza': require('../assets/audio/femenina/emociones/tristeza.mp3'),
    'enojo': require('../assets/audio/femenina/emociones/enojo.mp3'),
    'miedo': require('../assets/audio/femenina/emociones/miedo.mp3'),
    'sorpresa': require('../assets/audio/femenina/emociones/sorpresa.mp3'),
    'asco': require('../assets/audio/femenina/emociones/asco.mp3'),
    'feliz': require('../assets/audio/femenina/emociones/feliz.mp3'),
    'triste': require('../assets/audio/femenina/emociones/triste.mp3'),
    'enojado': require('../assets/audio/femenina/emociones/enojado.mp3'),
    'asustado': require('../assets/audio/femenina/emociones/asustado.mp3'),
    'cansado': require('../assets/audio/femenina/emociones/cansado.mp3'),
    'aburrido': require('../assets/audio/femenina/emociones/aburrido.mp3'),
    'confundido': require('../assets/audio/femenina/emociones/confundido.mp3'),

    // Comida categories
    'frutas': require('../assets/audio/femenina/comida/frutas.mp3'),
    'verduras': require('../assets/audio/femenina/comida/verduras.mp3'),
    'bebidas': require('../assets/audio/femenina/comida/bebidas.mp3'),
    'dulces': require('../assets/audio/femenina/comida/dulces.mp3'),
    'carnes': require('../assets/audio/femenina/comida/carnes.mp3'),

    // Frutas
    'manzana': require('../assets/audio/femenina/comida/frutas/manzana.mp3'),
    'platano': require('../assets/audio/femenina/comida/frutas/platano.mp3'),
    'fresas': require('../assets/audio/femenina/comida/frutas/fresas.mp3'),
    'uvas': require('../assets/audio/femenina/comida/frutas/uvas.mp3'),
    'naranja': require('../assets/audio/femenina/comida/frutas/naranja.mp3'),
    'mandarina': require('../assets/audio/femenina/comida/frutas/mandarina.mp3'),
    'pera': require('../assets/audio/femenina/comida/frutas/pera.mp3'),
    'sandia': require('../assets/audio/femenina/comida/frutas/sandia.mp3'),
    'mango': require('../assets/audio/femenina/comida/frutas/mango.mp3'),
    'durazno': require('../assets/audio/femenina/comida/frutas/durazno.mp3'),
    'pina': require('../assets/audio/femenina/comida/frutas/pina.mp3'),
    'limon': require('../assets/audio/femenina/comida/frutas/limon.mp3'),

    // Verduras
    'zanahoria': require('../assets/audio/femenina/comida/verduras/zanahoria.mp3'),
    'lechuga': require('../assets/audio/femenina/comida/verduras/lechuga.mp3'),
    'tomate': require('../assets/audio/femenina/comida/verduras/tomate.mp3'),
    'brocoli': require('../assets/audio/femenina/comida/verduras/brocoli.mp3'),
    'pepino': require('../assets/audio/femenina/comida/verduras/pepino.mp3'),
    'palta': require('../assets/audio/femenina/comida/verduras/palta.mp3'),
    'espinaca': require('../assets/audio/femenina/comida/verduras/espinaca.mp3'),
    'cebolla': require('../assets/audio/femenina/comida/verduras/cebolla.mp3'),
    'yuca': require('../assets/audio/femenina/comida/verduras/yuca.mp3'),
    'camote': require('../assets/audio/femenina/comida/verduras/camote.mp3'),
    'choclo': require('../assets/audio/femenina/comida/verduras/choclo.mp3'),
    'papa-vegetal': require('../assets/audio/femenina/comida/verduras/papa-vegetal.mp3'),

    // Bebidas
    'agua': require('../assets/audio/femenina/comida/bebidas/agua.mp3'),
    'leche': require('../assets/audio/femenina/comida/bebidas/leche.mp3'),
    'jugo': require('../assets/audio/femenina/comida/bebidas/jugo.mp3'),
    'chocolatada': require('../assets/audio/femenina/comida/bebidas/chocolatada.mp3'),
    'gaseosa': require('../assets/audio/femenina/comida/bebidas/gaseosa.mp3'),
    'limonada': require('../assets/audio/femenina/comida/bebidas/limonada.mp3'),

    // Lacteos items
    'queso': require('../assets/audio/femenina/comida/lacteos/queso.mp3'),
    'yogurt': require('../assets/audio/femenina/comida/lacteos/yogurt.mp3'),
    'mantequilla': require('../assets/audio/femenina/comida/lacteos/mantequilla.mp3'),
    'manjar': require('../assets/audio/femenina/comida/lacteos/manjar.mp3'),

    // Dulces
    'paleta': require('../assets/audio/femenina/comida/dulces/paleta.mp3'),
    'chocolate': require('../assets/audio/femenina/comida/dulces/chocolate.mp3'),
    'galleta': require('../assets/audio/femenina/comida/dulces/galleta.mp3'),
    'gelatina': require('../assets/audio/femenina/comida/dulces/gelatina.mp3'),
    'pan': require('../assets/audio/femenina/comida/dulces/pan.mp3'),

    // Carnes
    'pollo': require('../assets/audio/femenina/comida/carnes/pollo.mp3'),
    'tocino': require('../assets/audio/femenina/comida/carnes/tocino.mp3'),
    'carne': require('../assets/audio/femenina/comida/carnes/carne.mp3'),
    'pescado': require('../assets/audio/femenina/comida/carnes/pescado.mp3'),

    // Bano
    'inodoro': require('../assets/audio/femenina/baño/baño_item.mp3'),
    'papel': require('../assets/audio/femenina/baño/papel.mp3'),
    'ducharse': require('../assets/audio/femenina/baño/ducharse.mp3'),
    'lavado': require('../assets/audio/femenina/baño/lavado.mp3'),
    'dientes': require('../assets/audio/femenina/baño/dientes.mp3'),

    // Dormir
    'dormir-accion': require('../assets/audio/femenina/dormir/dormir_item.mp3'),
    'luz': require('../assets/audio/femenina/dormir/luz.mp3'),
    'osito': require('../assets/audio/femenina/dormir/osito.mp3'),
    'silencio': require('../assets/audio/femenina/dormir/silencio.mp3'),
    'cama': require('../assets/audio/femenina/dormir/cama.mp3'),
    'pijama': require('../assets/audio/femenina/dormir/pijama.mp3'),

    // Jugar
    'formas': require('../assets/audio/femenina/jugar/formas.mp3'),
    'animales': require('../assets/audio/femenina/jugar/animales.mp3'),
    'gestos': require('../assets/audio/femenina/jugar/gestos.mp3'),
    'j-emociones': require('../assets/audio/femenina/jugar/emociones_juego.mp3'),
    'pelota': require('../assets/audio/femenina/juguetes/pelota.mp3'),
    'carro': require('../assets/audio/femenina/juguetes/carro.mp3'),
    'legos': require('../assets/audio/femenina/juguetes/legos.mp3'),
    'dinosaurio': require('../assets/audio/femenina/juguetes/dinosaurio.mp3'),
    'muneca': require('../assets/audio/femenina/juguetes/muneca.mp3'),
    'tren': require('../assets/audio/femenina/juguetes/tren.mp3'),
    'plastilina': require('../assets/audio/femenina/juguetes/plastilina.mp3'),

    // Ropa
    'polo': require('../assets/audio/femenina/ropa/polo.mp3'),
    'pantalon': require('../assets/audio/femenina/ropa/pantalon.mp3'),
    'medias': require('../assets/audio/femenina/ropa/medias.mp3'),
    'casaca': require('../assets/audio/femenina/ropa/casaca.mp3'),
    'calzon': require('../assets/audio/femenina/ropa/calzon.mp3'),
    'zapatos': require('../assets/audio/femenina/ropa/zapatos.mp3'),
    'short': require('../assets/audio/femenina/ropa/short.mp3'),
    'zapatillas': require('../assets/audio/femenina/ropa/zapatillas.mp3'),
    'gorro': require('../assets/audio/femenina/ropa/gorro.mp3'),
    'chompa': require('../assets/audio/femenina/ropa/chompa.mp3'),
    'vestido': require('../assets/audio/femenina/ropa/vestido.mp3'),
    'falda': require('../assets/audio/femenina/ropa/falda.mp3'),

    // Quiero menu
    'comer': require('../assets/audio/femenina/quiero_menu/comer_q.mp3'),
    'television': require('../assets/audio/femenina/quiero_menu/television.mp3'),
    'papa': require('../assets/audio/femenina/quiero_menu/papa.mp3'),
    'mama': require('../assets/audio/femenina/quiero_menu/mama.mp3'),

    // No quiero menu
    'no-me-gusta': require('../assets/audio/femenina/no_quiero_menu/no_me_gusta.mp3'),
    'no-jugar': require('../assets/audio/femenina/no_quiero_menu/no_jugar.mp3'),
    'no-dormir': require('../assets/audio/femenina/no_quiero_menu/no_dormir.mp3'),
    'no-hablar': require('../assets/audio/femenina/no_quiero_menu/no_hablar.mp3'),
    'me-molesta': require('../assets/audio/femenina/no_quiero_menu/me_molesta.mp3'),

    // Mi dia / higiene
    'levantarse': require('../assets/audio/femenina/mi_dia/levantarse.mp3'),
    'cepillar-dientes': require('../assets/audio/femenina/mi_dia/cepillar-dientes.mp3'),
    'banarse': require('../assets/audio/femenina/mi_dia/banarse.mp3'),
    'lavar-cara': require('../assets/audio/femenina/mi_dia/lavar-cara.mp3'),
    'vestirse': require('../assets/audio/femenina/mi_dia/vestirse.mp3'),
    'desayunar': require('../assets/audio/femenina/mi_dia/desayunar.mp3'),
    'colegio': require('../assets/audio/femenina/mi_dia/colegio.mp3'),
    'llegar-casa': require('../assets/audio/femenina/mi_dia/llegar-casa.mp3'),
    'lavar-manos': require('../assets/audio/femenina/higiene/lavar-manos.mp3'),
    'peinarse': require('../assets/audio/femenina/higiene/peinarse.mp3'),

    // Personas
    'hermano': require('../assets/audio/femenina/personas/hermano.mp3'),
    'hermana': require('../assets/audio/femenina/personas/hermana.mp3'),
    'abuela': require('../assets/audio/femenina/personas/abuela.mp3'),
    'abuelo': require('../assets/audio/femenina/personas/abuelo.mp3'),
    'maestra': require('../assets/audio/femenina/personas/maestra.mp3'),
    'amigo': require('../assets/audio/femenina/personas/amigo.mp3'),
    'profe': require('../assets/audio/femenina/personas/profe.mp3'),
    'nico': require('../assets/audio/femenina/personas/nico.mp3'),

    // Social
    'hola': require('../assets/audio/femenina/social/hola.mp3'),
    'adios': require('../assets/audio/femenina/social/adios.mp3'),
    'gracias': require('../assets/audio/femenina/social/gracias.mp3'),
    'por-favor': require('../assets/audio/femenina/social/por-favor.mp3'),
    'si': require('../assets/audio/femenina/social/si.mp3'),
    'no': require('../assets/audio/femenina/social/no.mp3'),

    // Números (ítems)
    'uno': require('../assets/audio/femenina/numeros/uno.mp3'),
    'dos': require('../assets/audio/femenina/numeros/dos.mp3'),
    'tres': require('../assets/audio/femenina/numeros/tres.mp3'),
    'cuatro': require('../assets/audio/femenina/numeros/cuatro.mp3'),
    'cinco': require('../assets/audio/femenina/numeros/cinco.mp3'),
    'seis': require('../assets/audio/femenina/numeros/seis.mp3'),
    'siete': require('../assets/audio/femenina/numeros/siete.mp3'),
    'ocho': require('../assets/audio/femenina/numeros/ocho.mp3'),
    'nueve': require('../assets/audio/femenina/numeros/nueve.mp3'),
    'diez': require('../assets/audio/femenina/numeros/diez.mp3'),

    // Colores (ítems)
    'rojo': require('../assets/audio/femenina/colores/rojo.mp3'),
    'azul': require('../assets/audio/femenina/colores/azul.mp3'),
    'verde': require('../assets/audio/femenina/colores/verde.mp3'),
    'amarillo': require('../assets/audio/femenina/colores/amarillo.mp3'),
    'negro': require('../assets/audio/femenina/colores/negro.mp3'),
    'blanco': require('../assets/audio/femenina/colores/blanco.mp3'),

    // Tiempo
    'manana': require('../assets/audio/femenina/tiempo/manana.mp3'),
    'tarde': require('../assets/audio/femenina/tiempo/tarde.mp3'),
    'noche': require('../assets/audio/femenina/tiempo/noche.mp3'),
    'ahora': require('../assets/audio/femenina/tiempo/ahora.mp3'),
    'despues': require('../assets/audio/femenina/tiempo/despues.mp3'),

    // Lugar
    'casa': require('../assets/audio/femenina/lugar/casa.mp3'),
    'escuela': require('../assets/audio/femenina/lugar/escuela.mp3'),
    'parque': require('../assets/audio/femenina/lugar/parque.mp3'),
    'tienda': require('../assets/audio/femenina/lugar/tienda.mp3'),
    'medico': require('../assets/audio/femenina/lugar/medico.mp3'),

    // Tablero AAC
    'me-gusta': require('../assets/audio/femenina/tablero/me-gusta.mp3'),
    'ayuda': require('../assets/audio/femenina/tablero/ayuda.mp3'),
    'huevo': require('../assets/audio/femenina/tablero/huevo.mp3'),
    'arroz': require('../assets/audio/femenina/tablero/arroz.mp3'),
    'auto': require('../assets/audio/femenina/tablero/auto.mp3'),
    'estrella': require('../assets/audio/femenina/tablero/estrella.mp3'),
    'leer': require('../assets/audio/femenina/tablero/leer.mp3'),
    'caramelo': require('../assets/audio/femenina/tablero/caramelo.mp3'),
    'helado': require('../assets/audio/femenina/tablero/helado.mp3'),

    // Comida / menú
    'desayuno': require('../assets/audio/femenina/comida/menu/desayuno.mp3'),
    'almuerzo': require('../assets/audio/femenina/comida/menu/almuerzo.mp3'),
    'cena': require('../assets/audio/femenina/comida/menu/cena.mp3'),
    'snack': require('../assets/audio/femenina/comida/menu/snack.mp3'),

    // Avanzado
    'quiero-ir': require('../assets/audio/femenina/avanzado/yo-quiero/quiero-ir.mp3'),
    'quiero-comer': require('../assets/audio/femenina/avanzado/yo-quiero/quiero-comer.mp3'),
    'quiero-jugar': require('../assets/audio/femenina/avanzado/yo-quiero/quiero-jugar.mp3'),
    'quiero-ver': require('../assets/audio/femenina/avanzado/yo-quiero/quiero-ver.mp3'),
    'me-gusta-esto': require('../assets/audio/femenina/avanzado/me-gusta/me-gusta-esto.mp3'),
    'es-divertido': require('../assets/audio/femenina/avanzado/me-gusta/es-divertido.mp3'),
    'es-rico': require('../assets/audio/femenina/avanzado/me-gusta/es-rico.mp3'),
    'no-me-gusta-esto': require('../assets/audio/femenina/avanzado/no-me-gusta/no-me-gusta-esto.mp3'),
    'es-aburrido': require('../assets/audio/femenina/avanzado/no-me-gusta/es-aburrido.mp3'),
    'sabe-feo': require('../assets/audio/femenina/avanzado/no-me-gusta/sabe-feo.mp3'),
    'preguntar': require('../assets/audio/femenina/avanzado/hablar/preguntar.mp3'),
    'contar': require('../assets/audio/femenina/avanzado/hablar/contar.mp3'),
    'como-estas': require('../assets/audio/femenina/avanzado/hablar/como-estas.mp3'),
    'clase': require('../assets/audio/femenina/avanzado/escuela/clase.mp3'),
    'recreo': require('../assets/audio/femenina/avanzado/escuela/recreo.mp3'),
    'tarea': require('../assets/audio/femenina/avanzado/escuela/tarea.mp3'),
    'lapiz': require('../assets/audio/femenina/avanzado/escuela/lapiz.mp3'),
    'lunes': require('../assets/audio/femenina/avanzado/agenda/lunes.mp3'),
    'martes': require('../assets/audio/femenina/avanzado/agenda/martes.mp3'),
    'miercoles': require('../assets/audio/femenina/avanzado/agenda/miercoles.mp3'),
    'jueves': require('../assets/audio/femenina/avanzado/agenda/jueves.mp3'),
    'viernes': require('../assets/audio/femenina/avanzado/agenda/viernes.mp3'),
    'fin-semana': require('../assets/audio/femenina/avanzado/agenda/fin-semana.mp3'),
    'que-haces': require('../assets/audio/femenina/avanzado/conversaciones/que-haces.mp3'),
    'donde-vas': require('../assets/audio/femenina/avanzado/conversaciones/donde-vas.mp3'),
    'quien-es': require('../assets/audio/femenina/avanzado/conversaciones/quien-es.mp3'),
    'dolor': require('../assets/audio/femenina/avanzado/ayuda/dolor.mp3'),
    'perdido': require('../assets/audio/femenina/avanzado/ayuda/perdido.mp3'),
    'necesito-ayuda': require('../assets/audio/femenina/avanzado/ayuda/necesito-ayuda.mp3'),
    'ir': require('../assets/audio/femenina/avanzado/verbos/ir.mp3'),
    'venir': require('../assets/audio/femenina/avanzado/verbos/venir.mp3'),
    'dar': require('../assets/audio/femenina/avanzado/verbos/dar.mp3'),
    'tomar': require('../assets/audio/femenina/avanzado/verbos/tomar.mp3'),
    'ver': require('../assets/audio/femenina/avanzado/verbos/ver.mp3'),
    'escuchar': require('../assets/audio/femenina/avanzado/verbos/escuchar.mp3'),

    // Ejercicios (G2 / extras)
    'nervioso': require('../assets/audio/femenina/ejercicios/nervioso.mp3'),
    'bien': require('../assets/audio/femenina/ejercicios/bien.mp3'),
    'doctor': require('../assets/audio/femenina/ejercicios/doctor.mp3'),
};

const AUDIO_ASSETS_MASCULINA: Record<string, any> = {
    'yo': require('../assets/audio/masculina/dashboard/yo.mp3'),
    'comida': require('../assets/audio/masculina/dashboard/comida.mp3'),
    'emociones': require('../assets/audio/masculina/dashboard/emociones.mp3'),
    'bano': require('../assets/audio/masculina/dashboard/baño.mp3'),
    'dormir': require('../assets/audio/masculina/dashboard/dormir.mp3'),
    'jugar': require('../assets/audio/masculina/dashboard/jugar.mp3'),
    'ropa': require('../assets/audio/masculina/dashboard/ropa.mp3'),
    'quiero': require('../assets/audio/masculina/dashboard/quiero_si.mp3'),
    'no-quiero': require('../assets/audio/masculina/dashboard/no_quiero_no.mp3'),
    'juguetes': require('../assets/audio/masculina/dashboard/juguetes.mp3'),
    'mi-dia': require('../assets/audio/masculina/dashboard/mi_dia.mp3'),
    'lacteos': require('../assets/audio/masculina/dashboard/lacteos.mp3'),
    'personas': require('../assets/audio/masculina/dashboard/personas.mp3'),
    'lugar': require('../assets/audio/masculina/dashboard/lugar.mp3'),
    'hora': require('../assets/audio/masculina/dashboard/hora.mp3'),
    'social': require('../assets/audio/masculina/dashboard/social.mp3'),
    'numeros': require('../assets/audio/masculina/dashboard/numeros.mp3'),
    'colores': require('../assets/audio/masculina/dashboard/colores.mp3'),

    // Core words
    'core-yo': require('../assets/audio/masculina/core/core-yo.mp3'),
    'core-quiero': require('../assets/audio/masculina/core/core-quiero.mp3'),
    'core-no': require('../assets/audio/masculina/core/core-no.mp3'),
    'core-me-gustaria': require('../assets/audio/masculina/core/core-me-gustaria.mp3'),
    'core-necesito': require('../assets/audio/masculina/core/core-necesito.mp3'),
    'core-no-me-gusta': require('../assets/audio/masculina/core/core-no-me-gusta.mp3'),
    'core-hola': require('../assets/audio/masculina/core/core-hola.mp3'),
    'core-gracias': require('../assets/audio/masculina/core/core-gracias.mp3'),

    'mi-nombre': require('../assets/audio/masculina/yo/mi-nombre.mp3'),
    'tengo-calor': require('../assets/audio/masculina/yo/tengo-calor.mp3'),
    'tengo-frio': require('../assets/audio/masculina/yo/tengo-frio.mp3'),
    'tengo-hambre': require('../assets/audio/masculina/yo/tengo-hambre.mp3'),
    'tengo-sed': require('../assets/audio/masculina/yo/tengo-sed.mp3'),
    'estoy-cansado': require('../assets/audio/masculina/yo/estoy-cansado.mp3'),
    'me-duele': require('../assets/audio/masculina/yo/me-duele.mp3'),
    'me-llamo': require('../assets/audio/masculina/yo/me-llamo.mp3'),
    'yo-soy': require('../assets/audio/masculina/yo/yo-soy.mp3'),
    'mi-cumple': require('../assets/audio/masculina/yo/mi-cumple.mp3'),
    'tengo-x-anos': require('../assets/audio/masculina/yo/tengo-x-anos.mp3'),

    'calma': require('../assets/audio/masculina/emociones/calma.mp3'),
    'alegria': require('../assets/audio/masculina/emociones/alegria.mp3'),
    'tristeza': require('../assets/audio/masculina/emociones/tristeza.mp3'),
    'enojo': require('../assets/audio/masculina/emociones/enojo.mp3'),
    'miedo': require('../assets/audio/masculina/emociones/miedo.mp3'),
    'sorpresa': require('../assets/audio/masculina/emociones/sorpresa.mp3'),
    'asco': require('../assets/audio/masculina/emociones/asco.mp3'),
    'feliz': require('../assets/audio/masculina/emociones/feliz.mp3'),
    'triste': require('../assets/audio/masculina/emociones/triste.mp3'),
    'enojado': require('../assets/audio/masculina/emociones/enojado.mp3'),
    'asustado': require('../assets/audio/masculina/emociones/asustado.mp3'),
    'cansado': require('../assets/audio/masculina/emociones/cansado.mp3'),
    'aburrido': require('../assets/audio/masculina/emociones/aburrido.mp3'),
    'confundido': require('../assets/audio/masculina/emociones/confundido.mp3'),

    'frutas': require('../assets/audio/masculina/comida/frutas.mp3'),
    'verduras': require('../assets/audio/masculina/comida/verduras.mp3'),
    'bebidas': require('../assets/audio/masculina/comida/bebidas.mp3'),
    'dulces': require('../assets/audio/masculina/comida/dulces.mp3'),
    'carnes': require('../assets/audio/masculina/comida/carnes.mp3'),

    'manzana': require('../assets/audio/masculina/comida/frutas/manzana.mp3'),
    'platano': require('../assets/audio/masculina/comida/frutas/platano.mp3'),
    'fresas': require('../assets/audio/masculina/comida/frutas/fresas.mp3'),
    'uvas': require('../assets/audio/masculina/comida/frutas/uvas.mp3'),
    'naranja': require('../assets/audio/masculina/comida/frutas/naranja.mp3'),
    'mandarina': require('../assets/audio/masculina/comida/frutas/mandarina.mp3'),
    'pera': require('../assets/audio/masculina/comida/frutas/pera.mp3'),
    'sandia': require('../assets/audio/masculina/comida/frutas/sandia.mp3'),
    'mango': require('../assets/audio/masculina/comida/frutas/mango.mp3'),
    'durazno': require('../assets/audio/masculina/comida/frutas/durazno.mp3'),
    'pina': require('../assets/audio/masculina/comida/frutas/pina.mp3'),
    'limon': require('../assets/audio/masculina/comida/frutas/limon.mp3'),

    'zanahoria': require('../assets/audio/masculina/comida/verduras/zanahoria.mp3'),
    'lechuga': require('../assets/audio/masculina/comida/verduras/lechuga.mp3'),
    'tomate': require('../assets/audio/masculina/comida/verduras/tomate.mp3'),
    'brocoli': require('../assets/audio/masculina/comida/verduras/brocoli.mp3'),
    'pepino': require('../assets/audio/masculina/comida/verduras/pepino.mp3'),
    'palta': require('../assets/audio/masculina/comida/verduras/palta.mp3'),
    'espinaca': require('../assets/audio/masculina/comida/verduras/espinaca.mp3'),
    'cebolla': require('../assets/audio/masculina/comida/verduras/cebolla.mp3'),
    'yuca': require('../assets/audio/masculina/comida/verduras/yuca.mp3'),
    'camote': require('../assets/audio/masculina/comida/verduras/camote.mp3'),
    'choclo': require('../assets/audio/masculina/comida/verduras/choclo.mp3'),
    'papa-vegetal': require('../assets/audio/masculina/comida/verduras/papa-vegetal.mp3'),

    'agua': require('../assets/audio/masculina/comida/bebidas/agua.mp3'),
    'leche': require('../assets/audio/masculina/comida/bebidas/leche.mp3'),
    'jugo': require('../assets/audio/masculina/comida/bebidas/jugo.mp3'),
    'chocolatada': require('../assets/audio/masculina/comida/bebidas/chocolatada.mp3'),
    'gaseosa': require('../assets/audio/masculina/comida/bebidas/gaseosa.mp3'),
    'limonada': require('../assets/audio/masculina/comida/bebidas/limonada.mp3'),

    'queso': require('../assets/audio/masculina/comida/lacteos/queso.mp3'),
    'yogurt': require('../assets/audio/masculina/comida/lacteos/yogurt.mp3'),
    'mantequilla': require('../assets/audio/masculina/comida/lacteos/mantequilla.mp3'),
    'manjar': require('../assets/audio/masculina/comida/lacteos/manjar.mp3'),

    'paleta': require('../assets/audio/masculina/comida/dulces/paleta.mp3'),
    'chocolate': require('../assets/audio/masculina/comida/dulces/chocolate.mp3'),
    'galleta': require('../assets/audio/masculina/comida/dulces/galleta.mp3'),
    'gelatina': require('../assets/audio/masculina/comida/dulces/gelatina.mp3'),
    'pan': require('../assets/audio/masculina/comida/dulces/pan.mp3'),

    'pollo': require('../assets/audio/masculina/comida/carnes/pollo.mp3'),
    'tocino': require('../assets/audio/masculina/comida/carnes/tocino.mp3'),
    'carne': require('../assets/audio/masculina/comida/carnes/carne.mp3'),
    'pescado': require('../assets/audio/masculina/comida/carnes/pescado.mp3'),

    'inodoro': require('../assets/audio/masculina/baño/baño_item.mp3'),
    'papel': require('../assets/audio/masculina/baño/papel.mp3'),
    'ducharse': require('../assets/audio/masculina/baño/ducharse.mp3'),
    'lavado': require('../assets/audio/masculina/baño/lavado.mp3'),
    'dientes': require('../assets/audio/masculina/baño/dientes.mp3'),

    'dormir-accion': require('../assets/audio/masculina/dormir/dormir_item.mp3'),
    'luz': require('../assets/audio/masculina/dormir/luz.mp3'),
    'osito': require('../assets/audio/masculina/dormir/osito.mp3'),
    'silencio': require('../assets/audio/masculina/dormir/silencio.mp3'),
    'cama': require('../assets/audio/masculina/dormir/cama.mp3'),
    'pijama': require('../assets/audio/masculina/dormir/pijama.mp3'),

    'formas': require('../assets/audio/masculina/jugar/formas.mp3'),
    'animales': require('../assets/audio/masculina/jugar/animales.mp3'),
    'gestos': require('../assets/audio/masculina/jugar/gestos.mp3'),
    'j-emociones': require('../assets/audio/masculina/jugar/emociones_juego.mp3'),
    'pelota': require('../assets/audio/masculina/juguetes/pelota.mp3'),
    'carro': require('../assets/audio/masculina/juguetes/carro.mp3'),
    'legos': require('../assets/audio/masculina/juguetes/legos.mp3'),
    'dinosaurio': require('../assets/audio/masculina/juguetes/dinosaurio.mp3'),
    'muneca': require('../assets/audio/masculina/juguetes/muneca.mp3'),
    'tren': require('../assets/audio/masculina/juguetes/tren.mp3'),
    'plastilina': require('../assets/audio/masculina/juguetes/plastilina.mp3'),

    'polo': require('../assets/audio/masculina/ropa/polo.mp3'),
    'pantalon': require('../assets/audio/masculina/ropa/pantalon.mp3'),
    'medias': require('../assets/audio/masculina/ropa/medias.mp3'),
    'casaca': require('../assets/audio/masculina/ropa/casaca.mp3'),
    'calzon': require('../assets/audio/masculina/ropa/calzon.mp3'),
    'zapatos': require('../assets/audio/masculina/ropa/zapatos.mp3'),
    'short': require('../assets/audio/masculina/ropa/short.mp3'),
    'zapatillas': require('../assets/audio/masculina/ropa/zapatillas.mp3'),
    'gorro': require('../assets/audio/masculina/ropa/gorro.mp3'),
    'chompa': require('../assets/audio/masculina/ropa/chompa.mp3'),
    'vestido': require('../assets/audio/masculina/ropa/vestido.mp3'),
    'falda': require('../assets/audio/masculina/ropa/falda.mp3'),

    'comer': require('../assets/audio/masculina/quiero_menu/comer_q.mp3'),
    'television': require('../assets/audio/masculina/quiero_menu/television.mp3'),
    'papa': require('../assets/audio/masculina/quiero_menu/papa.mp3'),
    'mama': require('../assets/audio/masculina/quiero_menu/mama.mp3'),

    'no-me-gusta': require('../assets/audio/masculina/no_quiero_menu/no_me_gusta.mp3'),
    'no-jugar': require('../assets/audio/masculina/no_quiero_menu/no_jugar.mp3'),
    'no-dormir': require('../assets/audio/masculina/no_quiero_menu/no_dormir.mp3'),
    'no-hablar': require('../assets/audio/masculina/no_quiero_menu/no_hablar.mp3'),
    'me-molesta': require('../assets/audio/masculina/no_quiero_menu/me_molesta.mp3'),

    'levantarse': require('../assets/audio/masculina/mi_dia/levantarse.mp3'),
    'cepillar-dientes': require('../assets/audio/masculina/mi_dia/cepillar-dientes.mp3'),
    'banarse': require('../assets/audio/masculina/mi_dia/banarse.mp3'),
    'lavar-cara': require('../assets/audio/masculina/mi_dia/lavar-cara.mp3'),
    'vestirse': require('../assets/audio/masculina/mi_dia/vestirse.mp3'),
    'desayunar': require('../assets/audio/masculina/mi_dia/desayunar.mp3'),
    'colegio': require('../assets/audio/masculina/mi_dia/colegio.mp3'),
    'llegar-casa': require('../assets/audio/masculina/mi_dia/llegar-casa.mp3'),
    'lavar-manos': require('../assets/audio/masculina/higiene/lavar-manos.mp3'),
    'peinarse': require('../assets/audio/masculina/higiene/peinarse.mp3'),

    // Personas
    'hermano': require('../assets/audio/masculina/personas/hermano.mp3'),
    'hermana': require('../assets/audio/masculina/personas/hermana.mp3'),
    'abuela': require('../assets/audio/masculina/personas/abuela.mp3'),
    'abuelo': require('../assets/audio/masculina/personas/abuelo.mp3'),
    'maestra': require('../assets/audio/masculina/personas/maestra.mp3'),
    'amigo': require('../assets/audio/masculina/personas/amigo.mp3'),
    'profe': require('../assets/audio/masculina/personas/profe.mp3'),
    'nico': require('../assets/audio/masculina/personas/nico.mp3'),

    // Social
    'hola': require('../assets/audio/masculina/social/hola.mp3'),
    'adios': require('../assets/audio/masculina/social/adios.mp3'),
    'gracias': require('../assets/audio/masculina/social/gracias.mp3'),
    'por-favor': require('../assets/audio/masculina/social/por-favor.mp3'),
    'si': require('../assets/audio/masculina/social/si.mp3'),
    'no': require('../assets/audio/masculina/social/no.mp3'),

    // Números (ítems)
    'uno': require('../assets/audio/masculina/numeros/uno.mp3'),
    'dos': require('../assets/audio/masculina/numeros/dos.mp3'),
    'tres': require('../assets/audio/masculina/numeros/tres.mp3'),
    'cuatro': require('../assets/audio/masculina/numeros/cuatro.mp3'),
    'cinco': require('../assets/audio/masculina/numeros/cinco.mp3'),
    'seis': require('../assets/audio/masculina/numeros/seis.mp3'),
    'siete': require('../assets/audio/masculina/numeros/siete.mp3'),
    'ocho': require('../assets/audio/masculina/numeros/ocho.mp3'),
    'nueve': require('../assets/audio/masculina/numeros/nueve.mp3'),
    'diez': require('../assets/audio/masculina/numeros/diez.mp3'),

    // Colores (ítems)
    'rojo': require('../assets/audio/masculina/colores/rojo.mp3'),
    'azul': require('../assets/audio/masculina/colores/azul.mp3'),
    'verde': require('../assets/audio/masculina/colores/verde.mp3'),
    'amarillo': require('../assets/audio/masculina/colores/amarillo.mp3'),
    'negro': require('../assets/audio/masculina/colores/negro.mp3'),
    'blanco': require('../assets/audio/masculina/colores/blanco.mp3'),

    // Tiempo
    'manana': require('../assets/audio/masculina/tiempo/manana.mp3'),
    'tarde': require('../assets/audio/masculina/tiempo/tarde.mp3'),
    'noche': require('../assets/audio/masculina/tiempo/noche.mp3'),
    'ahora': require('../assets/audio/masculina/tiempo/ahora.mp3'),
    'despues': require('../assets/audio/masculina/tiempo/despues.mp3'),

    // Lugar
    'casa': require('../assets/audio/masculina/lugar/casa.mp3'),
    'escuela': require('../assets/audio/masculina/lugar/escuela.mp3'),
    'parque': require('../assets/audio/masculina/lugar/parque.mp3'),
    'tienda': require('../assets/audio/masculina/lugar/tienda.mp3'),
    'medico': require('../assets/audio/masculina/lugar/medico.mp3'),

    // Tablero AAC
    'me-gusta': require('../assets/audio/masculina/tablero/me-gusta.mp3'),
    'ayuda': require('../assets/audio/masculina/tablero/ayuda.mp3'),
    'huevo': require('../assets/audio/masculina/tablero/huevo.mp3'),
    'arroz': require('../assets/audio/masculina/tablero/arroz.mp3'),
    'auto': require('../assets/audio/masculina/tablero/auto.mp3'),
    'estrella': require('../assets/audio/masculina/tablero/estrella.mp3'),
    'leer': require('../assets/audio/masculina/tablero/leer.mp3'),
    'caramelo': require('../assets/audio/masculina/tablero/caramelo.mp3'),
    'helado': require('../assets/audio/masculina/tablero/helado.mp3'),

    // Comida / menú
    'desayuno': require('../assets/audio/masculina/comida/menu/desayuno.mp3'),
    'almuerzo': require('../assets/audio/masculina/comida/menu/almuerzo.mp3'),
    'cena': require('../assets/audio/masculina/comida/menu/cena.mp3'),
    'snack': require('../assets/audio/masculina/comida/menu/snack.mp3'),

    // Avanzado
    'quiero-ir': require('../assets/audio/masculina/avanzado/yo-quiero/quiero-ir.mp3'),
    'quiero-comer': require('../assets/audio/masculina/avanzado/yo-quiero/quiero-comer.mp3'),
    'quiero-jugar': require('../assets/audio/masculina/avanzado/yo-quiero/quiero-jugar.mp3'),
    'quiero-ver': require('../assets/audio/masculina/avanzado/yo-quiero/quiero-ver.mp3'),
    'me-gusta-esto': require('../assets/audio/masculina/avanzado/me-gusta/me-gusta-esto.mp3'),
    'es-divertido': require('../assets/audio/masculina/avanzado/me-gusta/es-divertido.mp3'),
    'es-rico': require('../assets/audio/masculina/avanzado/me-gusta/es-rico.mp3'),
    'no-me-gusta-esto': require('../assets/audio/masculina/avanzado/no-me-gusta/no-me-gusta-esto.mp3'),
    'es-aburrido': require('../assets/audio/masculina/avanzado/no-me-gusta/es-aburrido.mp3'),
    'sabe-feo': require('../assets/audio/masculina/avanzado/no-me-gusta/sabe-feo.mp3'),
    'preguntar': require('../assets/audio/masculina/avanzado/hablar/preguntar.mp3'),
    'contar': require('../assets/audio/masculina/avanzado/hablar/contar.mp3'),
    'como-estas': require('../assets/audio/masculina/avanzado/hablar/como-estas.mp3'),
    'clase': require('../assets/audio/masculina/avanzado/escuela/clase.mp3'),
    'recreo': require('../assets/audio/masculina/avanzado/escuela/recreo.mp3'),
    'tarea': require('../assets/audio/masculina/avanzado/escuela/tarea.mp3'),
    'lapiz': require('../assets/audio/masculina/avanzado/escuela/lapiz.mp3'),
    'lunes': require('../assets/audio/masculina/avanzado/agenda/lunes.mp3'),
    'martes': require('../assets/audio/masculina/avanzado/agenda/martes.mp3'),
    'miercoles': require('../assets/audio/masculina/avanzado/agenda/miercoles.mp3'),
    'jueves': require('../assets/audio/masculina/avanzado/agenda/jueves.mp3'),
    'viernes': require('../assets/audio/masculina/avanzado/agenda/viernes.mp3'),
    'fin-semana': require('../assets/audio/masculina/avanzado/agenda/fin-semana.mp3'),
    'que-haces': require('../assets/audio/masculina/avanzado/conversaciones/que-haces.mp3'),
    'donde-vas': require('../assets/audio/masculina/avanzado/conversaciones/donde-vas.mp3'),
    'quien-es': require('../assets/audio/masculina/avanzado/conversaciones/quien-es.mp3'),
    'dolor': require('../assets/audio/masculina/avanzado/ayuda/dolor.mp3'),
    'perdido': require('../assets/audio/masculina/avanzado/ayuda/perdido.mp3'),
    'necesito-ayuda': require('../assets/audio/masculina/avanzado/ayuda/necesito-ayuda.mp3'),
    'ir': require('../assets/audio/masculina/avanzado/verbos/ir.mp3'),
    'venir': require('../assets/audio/masculina/avanzado/verbos/venir.mp3'),
    'dar': require('../assets/audio/masculina/avanzado/verbos/dar.mp3'),
    'tomar': require('../assets/audio/masculina/avanzado/verbos/tomar.mp3'),
    'ver': require('../assets/audio/masculina/avanzado/verbos/ver.mp3'),
    'escuchar': require('../assets/audio/masculina/avanzado/verbos/escuchar.mp3'),

    // Ejercicios (G2 / extras)
    'nervioso': require('../assets/audio/masculina/ejercicios/nervioso.mp3'),
    'bien': require('../assets/audio/masculina/ejercicios/bien.mp3'),
    'doctor': require('../assets/audio/masculina/ejercicios/doctor.mp3'),
};

export type VoiceProfile = 'femenina' | 'masculina';

const PROFILE_MAP: Record<VoiceProfile, Record<string, any>> = {
    femenina: AUDIO_ASSETS_FEMENINA,
    masculina: AUDIO_ASSETS_MASCULINA,
};

export function getAudioAssets(profile: VoiceProfile = 'femenina'): Record<string, any> {
    const assets = PROFILE_MAP[profile];
    if (!assets || Object.keys(assets).length === 0) {
        return AUDIO_ASSETS_FEMENINA;
    }
    return { ...AUDIO_ASSETS_FEMENINA, ...assets };
}

export const AUDIO_ASSETS = AUDIO_ASSETS_FEMENINA;
